// ============================================
// ACTIVITY SUGGESTION ENGINE - TYPE DEFINITIONS
// ============================================
// Based on: docs/ACTIVITY_SUGGESTION_ALGORITHM.md

// ============================================
// CORE TYPES
// ============================================

/**
 * Coordinates for location-based operations
 */
export interface Coordinates {
  lat: number;
  lng: number;
}

/**
 * Localized address with support for local scripts
 */
export interface LocalizedAddress {
  formatted: string;
  localScript?: string; // e.g., Japanese characters
  postalCode?: string;
  city: string;
  country: string;
  neighborhood?: string;
}

/**
 * Entity resolution - canonical IDs to prevent duplicates/hallucinations
 */
export interface EntityIds {
  googlePlaceId?: string;
  yelpId?: string;
  viatorProductCode?: string;
  foursquareId?: string;
  internalId: string;
}

// ============================================
// ACTIVITY CATEGORIES
// ============================================

export type ActivityCategory =
  | "temple"
  | "shrine"
  | "museum"
  | "park"
  | "garden"
  | "landmark"
  | "neighborhood"
  | "market"
  | "shopping"
  | "entertainment"
  | "nature"
  | "viewpoint"
  | "cultural-experience"
  | "food-tour"
  | "walking-tour"
  | "day-trip"
  | "nightlife"
  | "relaxation"
  | "adventure"
  | "family-activity"
  | "photo-spot";

export type MealType = "breakfast" | "brunch" | "lunch" | "dinner" | "snack" | "cafe";

export type TimeOfDay = "early-morning" | "morning" | "afternoon" | "evening" | "night";

// ============================================
// ACTIVITY SOURCE TYPES
// ============================================

export type ActivitySource = "ai-generated" | "yelp" | "viator" | "google-places" | "user-suggested" | "curated";

/**
 * Core activity as generated by AI or curated
 */
export interface CoreActivity {
  id: string;
  entityIds: EntityIds;
  source: ActivitySource;

  // Basic info
  name: string;
  description: string;
  category: ActivityCategory;
  localTip?: string;

  // Location
  location: Coordinates;
  address: LocalizedAddress;
  neighborhood: string;

  // Timing
  bestTimeOfDay: TimeOfDay[];
  recommendedDuration: number; // minutes
  durationVariants?: ActivityVariants;

  // Scheduling constraints
  openingHours?: OpeningHours;
  closedDays?: number[]; // 0=Sunday, 6=Saturday
  seasonalClosure?: SeasonalClosure[];
  requiresBooking: boolean;
  bookingLeadTime?: number; // hours in advance

  // Cost
  isFree: boolean;
  estimatedCost?: MoneyAmount;
  childPricing?: MoneyAmount;

  // Audience fit
  familyFriendly: boolean;
  kidAges?: { min: number; max: number };
  romanticRating?: number; // 0-1
  soloFriendly: boolean;
  groupFriendly: boolean;
  accessibilityInfo?: AccessibilityInfo;

  // Weather sensitivity
  isOutdoor: boolean;
  weatherSensitive: boolean;
  rainAlternative?: string; // ID of indoor alternative

  // Ratings
  rating?: number;
  reviewCount?: number;

  // Media
  imageUrl?: string;
  images?: string[];

  // Tags for filtering
  tags: string[];

  // Metadata
  lastVerified?: Date;
  confidence: number; // 0-1, how confident we are in this data
}

/**
 * Restaurant activity with Yelp-specific fields
 */
export interface RestaurantActivity extends Omit<CoreActivity, "category"> {
  category: "restaurant";
  mealType: MealType[];
  cuisineTypes: string[];
  dietaryOptions: DietaryOption[];
  priceLevel: 1 | 2 | 3 | 4;
  reservationRequired: boolean;
  reservationUrl?: string;
  menuUrl?: string;
  hasKidsMenu: boolean;
  noiseLevel?: "quiet" | "moderate" | "loud";
}

/**
 * Viator bookable enhancement
 */
export interface ViatorEnhancement {
  productCode: string;
  title: string;
  description: string;
  price: MoneyAmount;
  duration: number; // minutes
  rating: number;
  reviewCount: number;
  bookingUrl: string;
  cancellationPolicy: string;
  includes: string[];
  highlights: string[];
  meetingPoint?: Coordinates;
  imageUrl: string;
}

// ============================================
// OPENING HOURS & SCHEDULING
// ============================================

export interface OpeningHours {
  regular: DayHours[];
  exceptions?: HoursException[];
}

export interface DayHours {
  day: number; // 0=Sunday, 6=Saturday
  open: string; // "09:00"
  close: string; // "17:00"
  lastEntry?: string; // "16:30"
}

export interface HoursException {
  date: string; // "2025-01-01"
  open?: string;
  close?: string;
  closed: boolean;
  reason?: string;
}

export interface SeasonalClosure {
  startDate: string; // "MM-DD"
  endDate: string;
  reason: string;
}

// ============================================
// MONEY & BUDGET
// ============================================

export interface MoneyAmount {
  amount: number;
  currency: string;
}

export type BudgetMode = "free-first" | "moderate" | "splurge-once-a-day";

export type BudgetLevel = "budget" | "moderate" | "luxury";

// ============================================
// DIETARY & ACCESSIBILITY
// ============================================

export type DietaryOption =
  | "vegetarian"
  | "vegan"
  | "pescatarian"
  | "gluten-free"
  | "halal"
  | "kosher"
  | "no-pork"
  | "no-beef"
  | "no-shellfish"
  | "nut-free"
  | "dairy-free";

export interface AccessibilityInfo {
  wheelchairAccessible: boolean;
  strollerFriendly: boolean;
  hasElevator: boolean;
  avoidStairs: boolean;
  hasAccessibleRestroom: boolean;
  serviceAnimalsAllowed: boolean;
  hearingAssistance?: boolean;
  visualAssistance?: boolean;
  notes?: string;
}

// ============================================
// TRIP MODE & TRAVELER COMPOSITION
// ============================================

export type TripMode =
  | "family"
  | "couples"
  | "solo"
  | "friends"
  | "multi-generational"
  | "girls-trip"
  | "guys-trip"
  | "honeymoon"
  | "babymoon";

export interface TravelerComposition {
  mode: TripMode;
  adults: number;
  children: number;
  childrenAges?: number[];
  seniors?: number; // 65+
  infants?: number; // under 2

  // Inferred from mode
  needsKidFriendly: boolean;
  needsRomantic: boolean;
  needsAccessible: boolean;
  allowsAdultVenues: boolean;
  prefersSocialSpots: boolean;
}

export interface TravelerConstraint {
visitorId: string;
  name: string;
  dietary: DietaryOption[];
  allergies: string[];
  accessibility?: AccessibilityInfo;
  mobilityLevel: "full" | "limited" | "requires-assistance";
  pace: "slow" | "moderate" | "fast";
}

// ============================================
// PACE & DAY PREFERENCES
// ============================================

export type PaceMode = "relaxed" | "normal" | "ambitious";

export type WalkingTolerance = "low" | "medium" | "high";

export type CommutePreference = "shortest" | "balanced" | "scenic";

export interface PaceSettings {
  mode: PaceMode;

  // Day timing
  dayStart: string; // "09:30"
  dayEnd: string; // "20:00"

  // Walking
  walkingTolerance: WalkingTolerance;
  maxWalkMinutes: number; // between activities

  // Rest
  napWindows?: TimeWindow[];
  breakFrequency: number; // minutes between breaks

  // Special modifiers
  jetLagDays?: number; // First N days slower
  noEarlyMornings?: boolean;
  poolTime?: {
    preferred: boolean;
    duration: number;
    timeOfDay: "morning" | "afternoon";
  };

  // Activity density
  minActivitiesPerDay: number;
  maxActivitiesPerDay: number;
}

export interface TimeWindow {
  start: string; // "13:00"
  end: string; // "15:00"
}

// ============================================
// ACTIVITY VARIANTS (SHORT/FULL/EXTENDED)
// ============================================

export interface ActivityVariants {
  short: VariantDetails;
  standard: VariantDetails;
  extended?: VariantDetails;
}

export interface VariantDetails {
  duration: number; // minutes
  description: string;
  covers: string[]; // what's included
  misses?: string[]; // what's skipped
  includes?: string[]; // special additions
  bestFor: string[];
}

// ============================================
// NIGHT ACTIVITIES
// ============================================

export type NightCategory =
  | "observatory"
  | "illumination"
  | "night-shrine"
  | "entertainment"
  | "dining"
  | "stroll"
  | "late-museum"
  | "soft-night";

export interface NightOperations {
  lastEntryTime?: string; // "21:00"
  closingTime?: string; // "22:00"
  openLateUntil?: string;
  seasonalNightOpen?: SeasonalNightHours[];

  // Family & safety
  ageRestricted?: boolean;
  minimumAge?: number;
  noiseLevel?: "quiet" | "normal" | "loud";
  lightingQuality?: "well-lit" | "dim" | "dark";
  nightSafetyScore?: number; // 0-1
  strollerFriendlyAtNight?: boolean;

  nightCategory?: NightCategory;
}

export interface SeasonalNightHours {
  start: string; // "2025-01-15"
  end: string;
  hours: string; // "until 22:00"
}

export interface NightBundle {
  id: string;
  name: string;
  description: string;
  familyFriendly: boolean;
  typicalDuration: number;
  pattern: string[];
  example: string;
  tips?: string[];
  seasonal?: { start: string; end: string };
  useWhen?: string[];
}

// ============================================
// SCORING & RANKING
// ============================================

export interface ScoringWeights {
  interestMatch: number; // default 25
  timeOfDayFit: number; // default 20
  durationFit: number; // default 15
  budgetMatch: number; // default 15
  weatherFit: number; // default 10
  varietyBonus: number; // default 10
  ratingBonus: number; // default 5
}

export interface NightScoringAdjustments {
  lateHoursFit: number; // +20
  transportFeasibility: number; // +15
  familySuitability: number; // +15
  indoorComfort: number; // +10
  vibeContinuity: number; // +10
  photoValue: number; // +5
}

export interface ModeScoringAdjustments {
  mode: TripMode;
  boosts: { tag: string; points: number }[];
  penalties: { tag: string; points: number }[];
  exclusions: string[]; // tags to exclude entirely
}

export interface ScoredActivity {
  activity: CoreActivity | RestaurantActivity;
  totalScore: number;
  scoreBreakdown: {
    interestMatch: number;
    timeOfDayFit: number;
    durationFit: number;
    budgetMatch: number;
    weatherFit: number;
    varietyBonus: number;
    ratingBonus: number;
    modeAdjustment: number;
    nightAdjustment?: number;
  };
  explanation: string; // "Chosen because: indoor, 10-min walk, fits 90min slot"
  confidence: number;
  warnings?: string[];
}

// ============================================
// COMMUTE & TRANSPORT
// ============================================

export type CommuteMethod = "walk" | "train" | "bus" | "taxi" | "subway" | "mixed";

export interface CommuteInfo {
  fromActivityId: string;
  toActivityId: string;
  method: CommuteMethod;
  durationMinutes: number;
  adjustedDuration?: number; // with kids/stroller adjustment
  distance: number; // meters
  cost?: MoneyAmount;
  instructions?: string;
  polyline?: string; // encoded route
}

export interface TransportGuardrails {
  lastTrainsToHotel: { [stationName: string]: string }; // "23:18"
  taxiFallback: {
    showWhen: string;
    estimatedCost: MoneyAmount;
    estimatedTime: number;
  };
}

// ============================================
// TIME SLOTS & SCHEDULING
// ============================================

export type SlotType = "activity" | "meal" | "commute" | "break" | "free" | "hotel";

export interface ScheduledSlot {
  id: string;
  type: SlotType;
  startTime: string; // "09:00"
  endTime: string; // "10:30"

  // Activity details (if type is activity or meal)
  activity?: CoreActivity | RestaurantActivity;
  selectedVariant?: "short" | "standard" | "extended";

  // Commute details (if type is commute)
  commute?: CommuteInfo;

  // Status
  isLocked: boolean; // user-confirmed, don't auto-adjust
  isBooked: boolean; // has a reservation
  bookingConfirmation?: string;

  // Alternatives
  alternatives?: ScoredActivity[];

  // Viator enhancement
  viatorEnhancement?: ViatorEnhancement;
}

export interface DaySchedule {
  date: string; // "2025-01-18"
  dayNumber: number;
  city: string;
  slots: ScheduledSlot[];
  weather?: WeatherForecast;
  totalWalkingMinutes: number;
  totalCost: MoneyAmount;
  hasRainPlan: boolean;
  rainPlanSlots?: ScheduledSlot[];
}

// ============================================
// WEATHER
// ============================================

export interface WeatherForecast {
  date: string;
  temperature: { min: number; max: number };
  condition: WeatherCondition;
  precipitationProbability: number;
  humidity: number;
  windSpeed: number;
  sunrise: string;
  sunset: string;
}

export type WeatherCondition =
  | "sunny"
  | "partly-cloudy"
  | "cloudy"
  | "rainy"
  | "heavy-rain"
  | "snowy"
  | "stormy"
  | "foggy";

// ============================================
// REAL-TIME FEATURES
// ============================================

// Energy Check-ins
export type EnergyLevel = "high" | "okay" | "low";

export interface EnergyCheckIn {
  timestamp: Date;
  level: EnergyLevel;
  context: {
    activitiesCompletedToday: number;
    walkingMinutesToday: number;
    lastMealTime: Date;
    weather: WeatherCondition;
  };
}

export interface EnergyAdjustment {
  action: "simplify" | "enhance" | "continue";
  changes: EnergyChange[];
  message: string;
}

export interface EnergyChange {
  type: "insert-break" | "shorten-next" | "skip-optional" | "reduce-walking" | "extend-current" | "add-activity";
  suggestion: string;
  savings?: string;
  cost?: MoneyAmount;
  options?: CoreActivity[];
}

// Nudges & Alerts
export type NudgeType =
  | "departure-reminder"
  | "booking-critical"
  | "last-entry-warning"
  | "last-train-alert"
  | "weather-change"
  | "grace-window"
  | "running-late"
  | "crowd-alert"
  | "nearby-opportunity"
  | "closing-soon";

export type NudgePriority = "critical" | "important" | "info";

export interface Nudge {
  id: string;
  type: NudgeType;
  priority: NudgePriority;
  title: string;
  body: string;
  actions: NudgeAction[];
  expiresAt: Date;
  dismissable: boolean;
  relatedSlotId?: string;
}

export interface NudgeAction {
  label: string;
  action: string; // "navigate" | "reschedule" | "book-taxi" | "dismiss"
  icon?: string;
  primary?: boolean;
}

// Grace Windows
export interface GraceWindow {
  venueType: string;
  defaultGraceMinutes: number;
  conditions: string;
}

export type GraceStatus = "on-time" | "grace" | "at-risk";

export interface GraceCheck {
  status: GraceStatus;
  message: string | null;
  lateByMinutes?: number;
  graceRemainingMinutes?: number;
}

// ============================================
// SWAP & RE-PLANNING
// ============================================

export interface SwapRequest {
  currentActivityId: string;
  reason?: "weather" | "closed" | "not-interested" | "too-crowded" | "user-request";
  constraints: {
    maxCommuteFromPrevious: number;
    maxCommuteToNext: number;
    preserveCategory: boolean;
    preserveBudget: boolean;
    preserveDuration: boolean;
  };
}

export interface SwapOption {
  activity: CoreActivity | RestaurantActivity;
  commuteFromPrevious: number;
  commuteToNext: number;
  categoryMatch: boolean;
  timingFit: boolean;
  reason: string;
  score: number;
}

export interface ReplanRequest {
  currentLocation: Coordinates;
  currentTime: Date;
  trigger: "user-request" | "location-detected" | "significant-delay" | "activity-skipped";
  preferences: {
    preserveBookings: boolean;
    preserveMustDos: boolean;
    maxCommuteToNext: number;
  };
}

export interface ReplanResult {
  originalPlan: ScheduledSlot[];
  newPlan: ScheduledSlot[];
  changes: PlanChange[];
  timeSavedMinutes: number;
}

export interface PlanChange {
  type: "moved" | "swapped" | "added" | "removed" | "shortened";
  activityId: string;
  activityName: string;
  fromDay?: number;
  toDay?: number;
  reason: string;
}

// ============================================
// OFFLINE MODE
// ============================================

export interface OfflinePackage {
  tripId: string;
  generatedAt: Date;
  expiresAt: Date;

  // Core data
  days: DaySchedule[];
  activities: (CoreActivity | RestaurantActivity)[];

  // Maps & navigation
  offlineMaps: {
    regions: string[];
    zoomLevels: number[];
    walkingRoutes: CommuteInfo[];
  };

  // Bookings
  bookings: {
    confirmationCodes: string[];
    qrCodes: string[];
    venueAddresses: LocalizedAddress[];
  };

  // Language helpers
  localLanguage: {
    venueNames: { [id: string]: string };
    venueAddresses: { [id: string]: string };
    phrasebook: Phrase[];
    emergencyPhrases: Phrase[];
  };

  // Exports
  exports: {
    dayPlanPDF?: string;
    calendarICS?: string;
  };

  sizeBytes: number;
}

export interface Phrase {
  english: string;
  local: string;
  pronunciation?: string;
  category: "greeting" | "directions" | "food" | "emergency" | "shopping" | "transport";
}

// ============================================
// VIEW PREFERENCES
// ============================================

export type ViewPreference = "map-first" | "timeline-first" | "split";

export interface ViewSettings {
  defaultView: ViewPreference;

  mapSettings: {
    showWalkingRoutes: boolean;
    showTransitLines: boolean;
    clusterNearbyPins: boolean;
    showNeighborhoodBoundaries: boolean;
  };

  timelineSettings: {
    showCommuteBlocks: boolean;
    showWeatherIcons: boolean;
    expandedByDefault: boolean;
    colorCodeByCategory: boolean;
  };
}

// ============================================
// USER EXPERIENCE SETTINGS (MASTER CONFIG)
// ============================================

export interface UserExperienceSettings {
  // Pace & Timing
  pace: PaceSettings;

  // Walking & Commute
  commutePreference: CommutePreference;
  avoidStairs: boolean;
  preferElevators: boolean;

  // Budget
  budgetMode: BudgetMode;
  dailyBudgetLimit?: MoneyAmount;
  showPricesIn: string; // currency code

  // Dietary & Accessibility
  dietary: DietaryOption[];
  allergies: string[];
  accessibility: AccessibilityInfo;

  // Trip Mode
  tripMode: TripMode;
  travelers: TravelerComposition;
  travelerConstraints?: TravelerConstraint[];

  // Anchors & Constraints
  anchors: {
    mustDo: string[]; // activity IDs
    niceToHave: string[];
    noGo: string[];
  };

  hardConstraints: {
    maxActivitiesPerDay?: number;
    requiredBreakFrequency?: number;
    kidsBedtime?: string;
    noEarlyMornings?: boolean;
  };

  // Weather
  rainPlanEnabled: boolean;
  weatherSensitivity: "low" | "medium" | "high";

  // Real-time Features
  energyCheckInsEnabled: boolean;
  checkInFrequency: "every-activity" | "twice-daily" | "manual";

  nudgeSettings: {
    departureReminders: boolean;
    lastTrainAlerts: boolean;
    weatherAlerts: boolean;
    crowdAlerts: boolean;
    graceWindowNotifications: boolean;
  };

  // View & Localization
  viewSettings: ViewSettings;
  showLocalScripts: boolean;
  language: string;

  // Notifications
  notifications: {
    enabled: boolean;
    criticalOnly: boolean;
    dnd?: TimeWindow;
    channels: ("push" | "email" | "sms")[];
  };

  // Offline
  offlineMode: {
    autoDownload: boolean;
    downloadDaysAhead: number;
    includeAlternatives: boolean;
    maxStorageMB: number;
  };

  // Advanced
  scoringWeights?: Partial<ScoringWeights>;
  vibePreferences?: string[];
  whatIfSimulation: boolean;
}

// ============================================
// DAY TEMPLATES
// ============================================

export interface DayTemplate {
  id: string;
  name: string;
  description: string;
  city: string;
  tripModes: TripMode[]; // which modes this works for
  duration: "half-day" | "full-day";
  slots: TemplateSlot[];
  features: string[];
  tags: string[];
  rating?: number;
  usageCount?: number;
}

export interface TemplateSlot {
  time: string;
  activityType: SlotType;
  activityId?: string; // specific activity
  activityCategory?: ActivityCategory; // or category to fill
  duration: number;
  notes?: string;
}

// ============================================
// API REQUEST/RESPONSE TYPES
// ============================================

export interface GenerateActivitiesRequest {
  destination: string;
  dates: { start: string; end: string };
  travelers: TravelerComposition;
  settings: Partial<UserExperienceSettings>;
  existingActivities?: string[]; // IDs to exclude
}

export interface GenerateActivitiesResponse {
  activities: ScoredActivity[];
  restaurants: ScoredActivity[];
  templates: DayTemplate[];
  warnings?: string[];
}

export interface BuildScheduleRequest {
  destination: string;
  dates: { start: string; end: string };
  activities: string[]; // selected activity IDs
  settings: UserExperienceSettings;
  hotel: Coordinates;
}

export interface BuildScheduleResponse {
  schedule: DaySchedule[];
  totalCost: MoneyAmount;
  totalWalkingMinutes: number;
  warnings?: string[];
  suggestions?: string[];
}

export interface SwapActivityRequest extends SwapRequest {
  currentSlot: ScheduledSlot;
  daySchedule: DaySchedule;
}

export interface SwapActivityResponse {
  options: SwapOption[];
  recommendation?: SwapOption;
}

export interface ReplanDayRequest extends ReplanRequest {
  daySchedule: DaySchedule;
  remainingDays: DaySchedule[];
}

export interface ReplanDayResponse extends ReplanResult {
  affectedDays: number[];
}

// ============================================
// TINDER-STYLE SELECTION
// ============================================

export type SwipeAction = "keep" | "reject" | "save-for-later" | "must-do";

export interface ActivitySwipe {
  activityId: string;
  action: SwipeAction;
  timestamp: Date;
}

export interface SelectionSession {
  sessionId: string;
  tripId: string;
  currentIndex: number;
  activities: ScoredActivity[];
  swipes: ActivitySwipe[];
  completed: boolean;
}

// ============================================
// EXPORTS
// ============================================

export type Activity = CoreActivity | RestaurantActivity;
